# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('ingredients', models.TextField(help_text='One indigrent per line', verbose_name='Indigrents')),
                ('preparation', models.TextField(verbose_name='Preparation')),
                ('time_for_preparation', models.IntegerField(blank=True, help_text='Time for preperation', null=True, verbose_name='Preparation time')),
                ('number_of_portions', models.PositiveIntegerField(verbose_name='Number of portions')),
                ('difficulty', models.SmallIntegerField(choices=[(1, 'easy'), (2, 'normal'), (3, 'hard')], default=2, verbose_name='Difficulty')),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_updated', models.DateTimeField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ManyToManyField(to='blog.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name_plural': 'Recipes',
                'ordering': ['-date_created'],
                'verbose_name': 'Recipe',
            },
        ),
    ]
