# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170515_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.CharField(choices=[(b'SOUP', 'soup'), (b'PASTA', 'pasta'), (b'DESSERT', 'dessert'), (b'SALAD', 'salad'), (b'STEW', 'stew')], default=b'SOUP', max_length=7),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[(b'EASY', 'easy'), (b'MEDIUM', 'normal'), (b'HARD', 'hard')], default=b'EASY', max_length=6),
        ),
    ]
